name: Playwright Tests

on:
  # push:
  #   branches: [ main, master ]   # Auto-run on push to these branches
  # pull_request:
  #   branches: [ main, master ]   # Auto-run on PR creation to these branches
  workflow_dispatch:               # Manual trigger only

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        # Checks out your repo code so the workflow can access it

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*       # Installs latest Node.js LTS version on runner

      - name: Install dependencies
        run: npm ci
        # Installs npm dependencies exactly as per package-lock.json

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        # Installs browsers needed by Playwright, plus OS dependencies

      - name: Run Playwright tests
        run: npx playwright test
        # Runs your Playwright test suite

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    permissions:
      contents: write           # Needed to push to gh-pages branch

    steps:
      - uses: actions/checkout@v4
        # Check out repo for deployment

      - name: Download Playwright report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Deploy Playwright report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          # Folder containing the Playwright HTML report to publish

      # - name: Print GitHub Pages URL
      #   run: echo "::notice::Playwright report available at https://rutbie.github.io/test-pw-gh/"

      - name: Add report link to job summary
        run: |
          echo "## 📊 Playwright Test Report" >> $GITHUB_STEP_SUMMARY
          echo "View the full test report here: [Open Report](https://rutbie.github.io/test-pw-gh/)" >> $GITHUB_STEP_SUMMARY
